# Generated by Django 4.0.6 on 2024-12-13 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciu', models.TextField()),
            ],
            options={
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id_mod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mod', models.TextField()),
            ],
            options={
                'db_table': 'modelo',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pro', models.TextField()),
                ('apellido_pro', models.TextField()),
                ('email_pro', models.CharField(max_length=50)),
                ('telefono_pro', models.CharField(max_length=15)),
                ('fk_id_ciu', models.ForeignKey(db_column='fk_id_ciu', on_delete=django.db.models.deletion.CASCADE, to='Agenda.ciudad')),
            ],
            options={
                'db_table': 'propietario',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_veh', models.AutoField(primary_key=True, serialize=False)),
                ('fabricacion_veh', models.CharField(max_length=30)),
                ('precio_veh', models.FloatField()),
                ('color_veh', models.CharField(max_length=30)),
                ('placa_veh', models.CharField(max_length=30)),
                ('fk_id_mod', models.ForeignKey(db_column='fk_id_mod', on_delete=django.db.models.deletion.CASCADE, to='Agenda.modelo')),
                ('fk_id_pro', models.ForeignKey(db_column='fk_id_pro', on_delete=django.db.models.deletion.CASCADE, to='Agenda.propietario')),
            ],
            options={
                'db_table': 'vehiculo',
            },
        ),
    ]
